services:
  server:
    image: bauer318/pri-trans-ui:latest
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 443:443
    networks:
      - pri-trans-ui_bridge
    volumes:
      - /etc/letsencrypt/live/pri-trans.com:/etc/ssl/private:ro
networks:
  pri-trans-ui_bridge:
    driver: bridge



